### ISSUE TITLE
Unable to find module while building a new cardboard project

### ISSUE THREAD

**Issue by lonnen** [boxen/cardboard#5]
First off -- apologies if this is the wrong place for this particular issue.

I'm writing a new module for BT Sync. I think I've got everything set up, but when I try to build it I get the following error:
```
Unable to find module 'boxen/puppet-boxen' on https://github.com
```
The code is at [lonnen/puppet-sync](https://github.com/lonnen/puppet-sync).

My machine has boxen set up. It has a dirty tree right now, but otherwise operates without error.

**Comment by seanknox** [comment]
@lonnen is this still an issue?

**Comment by lonnen** [comment]
I've long since walked away from this. Thank you for checking on it, though!
